# Generated by Django 4.2.4 on 2023-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_add_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='photo',
            field=models.ImageField(
                blank=True, upload_to='user_profile/photo/%Y/%m/%d/'
            ),
        ),
    ]
