# Generated by Django 4.2.4 on 2023-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_add_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
