# Generated by Django 4.2.4 on 2023-08-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_profiles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twits',
            name='answer_to_twit',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='answer',
                to='core.twits',
            ),
        ),
    ]
